[package]
name = "space_invaders"
version = "0.1.0"
edition = "2021"

[dependencies]
termion = "1.5.6"
rand = "0.8"
rodio = "0.17"

[build-dependencies]
fs_extra = "1.2"

[[bin]]
name = "space_invaders"
path = "src/main.rs"
